@GoodProductsApi_HostAddress = http://localhost:5148

GET {{GoodProductsApi_HostAddress}}/api/company/
Accept: application/json
###

GET {{GoodProductsApi_HostAddress}}/api/product/
Accept: application/json
###

GET {{GoodProductsApi_HostAddress}}/api/product/5
Accept: application/json
###

DELETE {{GoodProductsApi_HostAddress}}/api/product/5
Accept: application/json
###

POST {{GoodProductsApi_HostAddress}}/api/product
Content-Type: application/json
Accept: application/json

{
  "name": "Monkeys R Us",
  "price": 15.99,
  "companyId": 5
}
###

Put {{GoodProductsApi_HostAddress}}/api/product/
Content-Type: application/json
Accept: application/json

{
  "name": "Monkeys R Us",
  "price": 1.99,
  "id": 5
}
###
